package org.telegram.repostcleanerbot;

public interface Constants {
    String BOT_TOKEN = "REPOST_CLEANER_BOT_TOKEN";
    String BOT_NAME = "REPOST_CLEANER_BOT_NAME";
    String BOT_ADMIN_ID = "REPOST_CLEANER_BOT_ADMIN_ID";

    String BOT_API_ID = "REPOST_CLEANER_BOT_API_ID";
    String BOT_API_HASH = "REPOST_CLEANER_BOT_API_HASH";

    String BOT_MESSAGES_PROPERTY_FILE = "BotMessages";

    String AUTHENTICATION_QR_CODE_IMAGE_NAME = "qr_code";
    int AUTHENTICATION_QR_CODE_IMAGE_SIZE = 250;
    int ANALYZE_ALL_CHATS_LIMIT = 300;
    int CHATS_LIMIT = 300;

    interface INLINE_BUTTONS {
        String LOGIN = "LOGIN";

        String PHONE_NUMBER_LOGIN = "PHONE_NUMBER_LOGIN";
        String QR_CODE_LOGIN = "QR_CODE_LOGIN";

        String ALL_CHATS = "ALL_CHATS_FLOW";
        String SPECIFIC_CHAT = "SPECIFIC_CHAT_FLOW";

        String START_ANALYZING_ALL_CHATS = "START_ANALYZING_ALL_CHATS";
        String CANCEL_ANALYZING_ALL_CHATS = "CANCEL_ANALYZING_ALL_CHATS";
    }

    interface STATE_DB {
        String CLEAN_REPOSTS_FROM_ALL_CHATS_STATE_DB = "CLEAN_REPOSTS_FROM_ALL_CHATS_STATE_DB";
        String CLEAN_REPOSTS_FROM_SPECIFIC_CHAT_STATE_DB = "CLEAN_REPOSTS_FROM_SPECIFIC_CHAT_STATE_DB";

        String LOGIN_STATE_DB = "LOGIN_STATE_DB";
        String PHONE_NUMBER_ENTERING_STATE_DB = "PHONE_NUMBER_ENTERING_STATE_DB";
        String VERIFICATION_CODE_ENTERING_STATE_DB = "VERIFICATION_CODE_ENTERING_STATE_DB";
        String TWO_STEP_VERIFICATION_PASSWORD_ENTERING_STATE_DB = "TWO_STEP_VERIFICATION_PASSWORD_ENTERING_STATE_DB";
    }

    interface DB {
        String USER_CHATS = "USER_CHATS";
        String USER_REPOSTS_STAT_IN_SPECIFIC_CHANNEL = "USER_CHATS_REPOSTED_FROM";

        String USER_ALL_REPOSTS_GROUPED_BY_REPOSTED_FROM = "USER_ALL_REPOSTS_GROUPED_BY_REPOSTED_FROM";
    }
}
